openapi: 3.0.0
servers:
  - description: local
    url: http://127.0.0.1
    variables:
      version:
        default: v1
info:
  description: Реализация кредитного конвейера
  version: "1.0.0"
  title: API кредитного конвейера
tags:
  - name: "Conveyor Controller"
    description: "Контроллер для работы кредитного конвейера"
paths:
  /conveyor/offers:
    post:
      operationId: conveyor_offers
      summary: "Расчёт возможных условий кредита"
      description: "Расчёт возможных условий кредита"
      requestBody:
        description: Параметры запроса
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplicationRequestDto'
        required: true
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLoanOfferDto'
        400:
          description: 'Bad Request'
        422:
          description: 'Unporcessable Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /conveyor/calculation:
    post:
      operationId: conveyor_calculation
      summary: "Скоринг данных, полный расчет параметров кредита"
      description: "Скоринг данных, полный расчет параметров кредита"
      requestBody:
        description: Параметры запроса
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoringDataDto'
        required: true
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditDto'
        400:
          description: 'Bad Request'
        422:
          description: 'Unporcessable Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    LoanApplicationRequestDto:
      type: object
      description: 'Параметры запроса /offers'
      properties:
        amount:
          type: number
          format: int64
          minimum: 10000
          description: 'Сумма кредита'
          example: 10000
        term:
          type: integer
          minimum: 6
          description: 'Срок кредита'
          example: 6
        firstName:
          type: string
          minLength: 2
          maxLength: 30
          pattern: '[A-Za-zЁёА-я]{2,30}'
          description: 'Имя'
          example: 'Ivan'
        lastName:
          type: string
          minLength: 2
          maxLength: 30
          pattern: '[A-Za-zЁёА-я]{2,30}'
          description: 'Фамилия'
          example: 'Ivanov'
        middleName:
          type: string
          minLength: 2
          maxLength: 30
          pattern: '[A-Za-zЁёА-я]{2,30}'
          description: 'Отчество'
          example: 'Ivanovich'
          nullable: true
        email:
          type: string
          format: email
          maxLength: 70
          description: 'Email'
          example: 'mail@domain.com'
        birthdate:
          type: string
          format: date
          description: 'Дата рождения'
          example: '2000-01-01'
          x-constraints: AdultBirthDate
        passportSeries:
          type: string
          minLength: 4
          maxLength: 4
          pattern: '[0-9]{4}'
          description: 'Серия паспорта'
          example: '0000'
        passportNumber:
          type: string
          minLength: 6
          maxLength: 6
          pattern: '[0-9]{6}'
          description: 'Номер паспорта'
          example: '000000'
      required:
        - firstName
        - lastName
        - amount
        - term
        - passportNumber
        - passportSeries
        - email
        - birthdate
    ListLoanOfferDto:
      type: array
      description: 'Список кредитных предложений'
      items:
        $ref: '#/components/schemas/LoanOfferDto'
    LoanOfferDto:
      type: object
      description: 'Кредитное предложение'
      properties:
        applicationId:
          type: integer
          format: int64
          description: 'ИД заявки'
          example: 1
        requestedAmount:
          type: number
          format: int64
          description: 'Запрошенная сумма'
          example: 10000
        totalAmount:
          type: number
          format: int64
          description: 'Полная сумма'
          example: 10000
        term:
          type: integer
          description: 'Срок'
          example: 6
        monthlyPayment:
          type: number
          format: int64
          description: 'Месячный платеж'
          example: 10000
        rate:
          type: number
          format: int64
          description: 'Ставка'
          example: 10
        isInsuranceEnabled:
          type: boolean
          description: 'Страховка включена'
          example: true
        isSalaryClient:
          type: boolean
          description: 'Зарплатный клиент'
          example: true
    ScoringDataDto:
      type: object
      description: ''
      properties:
        amount:
          type: number
          format: int64
          minimum: 10000
          description: 'Сумма кредита'
          example: 10000
        term:
          type: integer
          minimum: 6
          description: 'Срок кредита'
          example: 6
        firstName:
          type: string
          minLength: 2
          maxLength: 30
          pattern: '[A-Za-zЁёА-я]{2,30}'
          description: 'Имя'
          example: 'Ivan'
        lastName:
          type: string
          minLength: 2
          maxLength: 30
          pattern: '[A-Za-zЁёА-я]{2,30}'
          description: 'Фамилия'
          example: 'Ivanov'
        middleName:
          type: string
          minLength: 2
          maxLength: 30
          pattern: '[A-Za-zЁёА-я]{2,30}'
          description: 'Отчество'
          example: 'Ivanovich'
          nullable: true
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - NON_BINARY
          description: 'Пол'
          example: 'MALE'
        birthdate:
          type: string
          format: date
          description: 'Дата рождения'
          example: '2000-01-01'
        passportSeries:
          type: string
          minLength: 4
          maxLength: 4
          pattern: '[0-9]{4}'
          description: 'Серия паспорта'
          example: '0000'
        passportNumber:
          type: string
          minLength: 6
          maxLength: 6
          pattern: '[0-9]{6}'
          description: 'Номер паспорта'
          example: '000000'
        passportIssueDate:
          type: string
          format: date
          description: 'Дата выдачи паспорта'
          example: '2000-01-01'
        passportIssueBranch:
          type: string
          description: 'Отделение'
          example: 'Отделение'
        maritalStatus:
          type: string
          enum:
            - MARRIED
            - DIVORCED
            - SINGLE
            - WIDOW_WIDOWER
          description: 'Семейное положение'
          example: 'MARRIED'
        dependentAmount:
          type: integer
          minimum: 0
          description: 'Кол-во иждивенцев'
          example: 1
        employment:
          $ref: '#/components/schemas/EmploymentDto'
        account:
          type: string
          pattern: '[0-9]{20}'
          description: 'Номер счета'
          example: '09876543211234567890'
        isInsuranceEnabled:
          type: boolean
          description: 'Страховка включена'
          example: true
        isSalaryClient:
          type: boolean
          description: 'Зарплатный клиент'
          example: true
      required:
        - amount
        - term
        - firstName
        - lastName
        - gender
        - birthdate
        - passportSeries
        - passportNumber
        - maritalStatus
        - dependentAmount
        - employment
        - account
        - isInsuranceEnabled
        - isSalaryClient
    CreditDto:
      type: object
      description: 'Параметры кредита'
      properties:
        amount:
          type: number
          format: int64
          description: 'Сумма кредита'
          example: 10000
        term:
          type: integer
          description: 'Срок кредита'
          example: 6
        monthlyPayment:
          type: number
          format: int64
          description: 'Месячный платеж'
          example: 10000
        rate:
          type: number
          format: int64
          description: 'Ставка'
          example: 10
        psk:
          type: number
          format: int64
          description: 'Полная стоимость кредита'
          example: 10000
        isInsuranceEnabled:
          type: boolean
          description: 'Страховка включена'
          example: true
        isSalaryClient:
          type: boolean
          description: 'Зарплатный клиент'
          example: true
        paymentSchedule:
          type: array
          items:
            $ref: '#/components/schemas/PaymentScheduleElement'
    EmploymentDto:
      type: object
      description: 'Трудоустройство'
      properties:
        employmentStatus:
          type: string
          enum:
            - UNEMPLOYED
            - SELF_EMPLOYED
            - EMPLOYED
            - BUSINESS_OWNER
          description: 'Статус трудоустройства'
          example: 'EMPLOYED'
        employerInn:
          type: string
          pattern: '[0-9]{10,12}'
          description: 'ИНН'
          example: '123456789012'
        salary:
          type: number
          format: int64
          description: 'Размер ЗП'
          example: 10000
        position:
          type: string
          enum:
            - WORKER
            - MID_MANAGER
            - TOP_MANAGER
            - OWNER
          description: 'Должность'
          example: 'WORKER'
        workExperienceTotal:
          type: integer
          description: 'Общий трудовой стаж'
          example: 5
        workExperienceCurrent:
          type: integer
          description: 'Трудовой стаж на текущем месте'
          example: 5
      required:
        - employmentStatus
        - employerInn
        - workExperienceTotal
        - workExperienceCurrent
    PaymentScheduleElement:
      type: object
      description: 'График выплат'
      properties:
        number:
          type: integer
          description: 'Номер платежа'
          example: 1
        date:
          type: string
          format: date
          description: 'Дата платежа'
          example: '2000-01-01'
        totalPayment:
          type: number
          format: int64
          description: 'Сумма платжеа'
          example: 1000
        interestPayment:
          type: number
          format: int64
          description: 'На выплату процентов'
          example: 1000
        debtPayment:
          type: number
          format: int64
          description: 'На выплату долга'
          example: 1000
        remainingDebt:
          type: number
          format: int64
          description: 'Остаток долга'
          example: 1000
    ErrorMessage:
      type: object
      description: 'Сообщение об ошибке'
      properties:
        timestamp:
          type: string
          format: date-time
          description: 'Дата и время ошибки'
        exception:
          type: string
          description: 'Исключение'
        status:
          type: integer
          description: 'Статус код'
        error:
          type: string
          description: 'Ошибка'
        path:
          type: string
          description: 'Путь'
        message:
          type: string
          description: 'Сообщение об ошибке'